# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Ruby

on:
  push:
    branches: ["master", "ruby-v3x"]
  pull_request:
    branches: ["master", "ruby-v3x"]

permissions:
  contents: read

jobs:
  lint_and_test:
    env:
      RACK_ENV: test
      COVERAGE: "true"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby-version: ["3.0", "3.1", "3.2", "3.3"]
        # Disable JRuby for now
        # ruby-version: ["3.0", "3.1", "3.2", "3.3", "jruby-9.4"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run rake (lint and test)
        run: bundle exec rake
